[versions]
agp = "8.3.2"                               # https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google                https://developer.android.com/studio/releases/gradle-plugin
r8 = "8.4.23"                               # https://r8.googlesource.com/r8/+/refs/heads/8.4                                              https://r8.googlesource.com/r8/
bundleTool = "1.15.6"                       # https://mvnrepository.com/artifact/com.android.tools.build/bundletool                        https://github.com/google/bundletool

kotlin = "1.9.23"                           # https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib                        https://blog.jetbrains.com/kotlin/category/releases/

androidx-activity = "1.9.0-rc01"            # https://mvnrepository.com/artifact/androidx.activity/activity                                https://developer.android.com/jetpack/androidx/releases/activity

androidx-compose-compiler = "1.5.11"        # https://mvnrepository.com/artifact/androidx.compose.compiler/compiler                        https://developer.android.com/jetpack/androidx/releases/compose-compiler
androidx-compose-ui = "1.7.0-alpha06"       # https://mvnrepository.com/artifact/androidx.compose.ui/ui                                    https://developer.android.com/jetpack/androidx/releases/compose-ui
androidx-compose-material3 = "1.3.0-alpha04"# https://mvnrepository.com/artifact/androidx.compose.material3/material3                      https://developer.android.com/jetpack/androidx/releases/compose-material3

[plugins]
android = { id = "com.android.tools.build:gradle", version.ref = "agp" }
r8 = { id = "com.android.tools:r8", version.ref = "r8" }
kotlin = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
bundleTool = { id = "com.android.tools.build:bundletool", version.ref = "bundleTool" }

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlibCommon = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "kotlin" }
kotlin-stdlibJdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-stdlibJdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-ui" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }